
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salehalmakki
 */
public class Form_Tasks extends javax.swing.JFrame {

    private User user;
    private ArrayList receivedTasks;
    private ArrayList sentTasks;
    private ArrayList closedTasks;
    private ArrayList users_array;
    private TasksTable tasksTable = new TasksTable();
    private Form_UserSettings settings_form;
    
    
    public Form_Tasks(User user) {
        initComponents();
        Tool tool = new Tool();
        tool.CenterForm(this);
        this.user = user;
        settings_form = new Form_UserSettings(user, this);
        
        //receivedTasks = tasksTable.getReceivedTasks(user.getUsername());
        //sentTasks = tasksTable.getSentTasks(user.getUsername());
        //closedTasks = tasksTable.getClosedTasks(user.getUsername());
        
        ArrayList user_tasks = new TasksTable().getUserTasks(user.getUsername());
        tool.filterTasks(user.getUsername(), user_tasks);
        receivedTasks = tool.receivedTasks;
        sentTasks = tool.sentTasks;
        closedTasks = tool.closedTasks;
        
        lstMenu.setSelectedIndex(0);
        callRequestsToCloseTasks();
        lblLastUpdated.setText("Last updated: " + new Date().toString());
        //updateClosedTaskTable();
        //btnClose.setEnabled(false);
        //btnReturn.setEnabled(false);
    }

    private void updateTable(){
        
        DefaultTableModel dm = (DefaultTableModel)tblTasks.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

        ArrayList array;
        if (lstMenu.getSelectedIndex() == 0) array = receivedTasks;
        else array = sentTasks;
        
        boolean showAll = chkShowCompleted.isSelected();
        
        for(int i = 0; i < array.size(); i++){
            Task task = (Task) array.get(i);
            if(showAll || task.getStatus() == 0){
                Object[] row = { task.getTaskID(),
                        lstMenu.getSelectedIndex() == 0? task.getAssignor():task.getAssignee(), 
                        task.getSubject(), task.getDueDate()};
                dm.addRow(row);
            }
        }
    } 
    
    private void updateClosedTaskTable(){
        
        DefaultTableModel dm = (DefaultTableModel)tblTasksToClose.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

        for(int i = 0; i < closedTasks.size(); i++){
            Task task = (Task) closedTasks.get(i);
            Object[] row = { task.getTaskID(), task.getAssignee(), task.getSubject(), 
                task.getDueDate(), task.getStatus()==1?"Completed":"Closed"};
                dm.addRow(row);
        }
    } 
    
    private void callRequestsToCloseTasks(){
        for(int i = 0; i < closedTasks.size(); i++){
            Task task = (Task) closedTasks.get(i);
            String status = "";
            
            if(task.getStatus() == 0) status ="In progress";
            else if(task.getStatus() == 1) status ="Completed";
            else if(task.getStatus() == 0) status ="Closed";
            Object[] row = { task.getTaskID(), task.getAssignee(), task.getSubject(), task.getDueDate()};
            DefaultTableModel model = (DefaultTableModel) tblTasksToClose.getModel();
            model.addRow(row);
        }
    }
            

    
    
    public void setMenuSelection(int value){
        lstMenu.setSelectedIndex(value);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkShowCompleted = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMenu = new javax.swing.JList();
        lblTitle = new javax.swing.JLabel();
        lblTasksToClose = new javax.swing.JLabel();
        lblNewTask = new javax.swing.JLabel();
        pnlTasksToClose = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTasksToClose = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        pnlTasks = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        lblRefresh = new javax.swing.JLabel();
        lblLastUpdated = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkShowCompleted.setText("Show completed tasks");
        chkShowCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowCompletedActionPerformed(evt);
            }
        });

        lstMenu.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "My Tasks", "Sent Tasks", "Settings" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstMenu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMenuValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstMenu);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitle.setText("My Tasks");

        lblTasksToClose.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTasksToClose.setText("Requests to close");

        lblNewTask.setForeground(new java.awt.Color(0, 0, 255));
        lblNewTask.setText("New Task");
        lblNewTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNewTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewTaskMouseClicked(evt);
            }
        });

        tblTasksToClose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "User", "Subject", "Due Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTasksToClose.setName("tasksBox"); // NOI18N
        tblTasksToClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTasksToCloseMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTasksToClose);
        if (tblTasksToClose.getColumnModel().getColumnCount() > 0) {
            tblTasksToClose.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblTasksToClose.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblTasksToClose.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblTasksToClose.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblTasksToClose.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout pnlTasksToCloseLayout = new javax.swing.GroupLayout(pnlTasksToClose);
        pnlTasksToClose.setLayout(pnlTasksToCloseLayout);
        pnlTasksToCloseLayout.setHorizontalGroup(
            pnlTasksToCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlTasksToCloseLayout.setVerticalGroup(
            pnlTasksToCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTasksToCloseLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnClose.setText("Close");
        btnClose.setEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnReturn.setForeground(new java.awt.Color(255, 0, 0));
        btnReturn.setText("Return");
        btnReturn.setEnabled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "User", "Subject", "Due Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTasks.setName("tasksBox"); // NOI18N
        tblTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTasksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTasks);
        if (tblTasks.getColumnModel().getColumnCount() > 0) {
            tblTasks.getColumnModel().getColumn(0).setResizable(false);
            tblTasks.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblTasks.getColumnModel().getColumn(1).setResizable(false);
            tblTasks.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblTasks.getColumnModel().getColumn(2).setResizable(false);
            tblTasks.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblTasks.getColumnModel().getColumn(3).setResizable(false);
            tblTasks.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        javax.swing.GroupLayout pnlTasksLayout = new javax.swing.GroupLayout(pnlTasks);
        pnlTasks.setLayout(pnlTasksLayout);
        pnlTasksLayout.setHorizontalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTasksLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTasksLayout.setVerticalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTasksLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblRefresh.setForeground(new java.awt.Color(150, 0, 0));
        lblRefresh.setText("Refresh");
        lblRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefreshMouseClicked(evt);
            }
        });

        lblLastUpdated.setForeground(new java.awt.Color(0, 110, 0));
        lblLastUpdated.setText("Last Updated");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTasksToClose)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLastUpdated)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRefresh))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnClose)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnlTasksToClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(chkShowCompleted)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewTask))
                        .addComponent(pnlTasks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(225, 225, 225))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkShowCompleted)
                    .addComponent(lblNewTask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblTasksToClose, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTasksToClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnReturn))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRefresh)
                    .addComponent(lblLastUpdated))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkShowCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowCompletedActionPerformed
        updateTable();
    }//GEN-LAST:event_chkShowCompletedActionPerformed

    private void tblTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTasksMouseClicked
        if (evt.getClickCount() == 2){
            int row = tblTasks.getSelectedRow();

            if (lstMenu.getSelectedIndex() == 0){
                Task task = (Task) receivedTasks.get(row);
                new Dialog_Task(user, task, this, 3).setVisible(true);
            }
                
            else if (lstMenu.getSelectedIndex() == 1){
                Task task = (Task) sentTasks.get(row);
                new Dialog_Task(user, task, this, 2).setVisible(true);
            }
            else{
                return;
            }
               
            //if(needsUpdateTasksTable){
            //    updateTable();
            //    needsUpdateTasksTable=false;
            //}
                
        }
    }//GEN-LAST:event_tblTasksMouseClicked
    
    public void insertRow(Task task){
        Object[] row = { task.getTaskID(), task.getAssignee(), task.getSubject(), task.getDueDate()};
        DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();
        model.addRow(row);
        this.sentTasks.add(task);
    }
        
    private boolean needsUpdateTasksTable=false;
    public void notifyNeedsUpdateTasksTable(){
        needsUpdateTasksTable = true;
    }
    
    private void tblTasksToCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTasksToCloseMouseClicked
         if (evt.getClickCount() == 2){
            int row = tblTasksToClose.getSelectedRow();
            long task_id = (long) tblTasksToClose.getValueAt(row, 0);
            Task task = tasksTable.getTask(task_id);
            new Dialog_Task(user, task, this, 4).setVisible(true);
         }
         
         
        if(tblTasksToClose.getSelectedRowCount() == 1){
            btnClose.setEnabled(true);
            btnReturn.setEnabled(true);
        }
        else{
            btnClose.setEnabled(false);
            btnReturn.setEnabled(false);
        }
    }//GEN-LAST:event_tblTasksToCloseMouseClicked

    private void lblNewTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewTaskMouseClicked
        new Dialog_Task(user, new Task(), this, 1).setVisible(true);
    }//GEN-LAST:event_lblNewTaskMouseClicked

    
    private void lstMenuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMenuValueChanged
        //System.out.println(tblTasks.getWidth() + ", " + tblTasks.getHeight());
        
        if(lstMenu.getSelectedIndex()==0){
            //tblTasks.setSize(531, 20);
            lblTitle.setText("My Tasks");
            lblNewTask.hide();
            pnlTasksToClose.hide();
            lblTasksToClose.hide();
            btnClose.hide();
            btnReturn.hide();
            updateTable();
        }
        else if(lstMenu.getSelectedIndex()==1){
            lblTitle.setText("Sent Tasks");
            lblNewTask.show();
            pnlTasksToClose.show();
            lblTasksToClose.show();
            btnClose.show();
            btnReturn.show();
            updateTable();
        }
          
        else if(lstMenu.getSelectedIndex()==2){
            settings_form.setVisible(true);
            settings_form.setMenuSelection(2);
            this.setVisible(false);
        }
    }//GEN-LAST:event_lstMenuValueChanged

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        if (tblTasksToClose.getSelectedRowCount() == 0)
            return;
        
        int row = tblTasksToClose.getSelectedRow();
        long task_id = (long) tblTasksToClose.getValueAt(row, 0);
        tasksTable.updateStatus(task_id, 0);
        tblTasksToClose.remove(row);

    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        if (tblTasksToClose.getSelectedRowCount() == 0)
            return;
        
        int row = tblTasksToClose.getSelectedRow();
        long task_id = (long) tblTasksToClose.getValueAt(row, 0);
        int status = (int) tblTasksToClose.getValueAt(row, 3);
        if (status == 1)
            tasksTable.updateStatus(task_id, -1);
        else if(status == -2)
            tasksTable.updateStatus(task_id, -2);
        
        tblTasksToClose.remove(row);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void lblRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshMouseClicked
        receivedTasks = tasksTable.getReceivedTasks(user.getUsername());
        //sentTasks is already up to date
        closedTasks = tasksTable.getClosedTasks(user.getUsername());
        updateTable();
        updateClosedTaskTable();
        lblLastUpdated.setText("Last updated: " + new Date().toString());
    }//GEN-LAST:event_lblRefreshMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReturn;
    private javax.swing.JCheckBox chkShowCompleted;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblNewTask;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblTasksToClose;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList lstMenu;
    private javax.swing.JPanel pnlTasks;
    private javax.swing.JPanel pnlTasksToClose;
    private javax.swing.JTable tblTasks;
    private javax.swing.JTable tblTasksToClose;
    // End of variables declaration//GEN-END:variables
}
